import os 
import re

def parse_label(answer):
    """
        Function to parse the actual answer given by the LLM. 

        :answer: answer generated by the model

        return: "entailment"/"contradiction" (string) 
    """

    # TODO add all possible terms 
    CONTRADICTION_TERMS = ['contradiction']
    ENTAILMENT_TERMS = ['entailment']

    # non-case sensitive 